### ISSUE TITLE
The reason public initialiser isn't available for LocationManager?

### ISSUE THREAD

**Issue by andreyz** [pointfreeco/composable-core-location#17]
It's been great to have `.failing` becoming available after recent modernisation, which naturally leads to implementing a `.noop` version of the dependency too, but it isn't possible currently. Was there a reason for keeping `init` internal?

**Comment by stephencelis** [comment]
No reason, I don't think! I think we're relying on the synthesized memberwise initializer. If you'd like to PR an explicit, public one I don't see anything wrong with adding it! I could also see including the `.noop` version in the PR.
