### ISSUE TITLE
Delegate must respond to locationManager:didUpdateLocations: 

### ISSUE THREAD

**Issue by saroar** [pointfreeco/composable-core-location#23]
i dont understand why its always crashing i am using main branch 
// And/or enter code that reproduces the behavior here.
https://gist.github.com/saroar/abdb5ec787246d150e66be1a4cb7d03b

**Expected behavior**
Give a clear and concise description of what you expected to happen.

**Screenshots**

**Environment**
 - Xcode 13
 - Swift 5.5
 - OS (15.0): [e.g. iOS 13]

**Additional context**
Add any more context about the problem here.

**Comment by mbrandonw** [comment]
Closing this issue since it was asked in the TCA repo: https://github.com/pointfreeco/swift-composable-architecture/discussions/877
