### ISSUE TITLE
CCL dependency on TCA conflicts with dependency on TCA

### ISSUE THREAD

**Issue by ferologics** [pointfreeco/composable-core-location#25]
**Describe the bug**
In projects that depend on both TCA and CCL Xcode raises the following warning during SPM package resolution:
```
'composable-core-location' dependency on 'https://github.com/pointfreeco/swift-composable-architecture' conflicts with dependency on 'https://github.com/pointfreeco/swift-composable-architecture' which has the same identity 'swift-composable-architecture'. this will be escalated to an error in future versions of SwiftPM.
```

**To Reproduce**
1. Create a new project
2. Add TCA and CCL as dependencies
3. Reset package caches
4. Observe warning

**Expected behavior**
No warning during SPM package resolution.

**Environment**
 - Xcode Version `13.3 (13E113)`
 - Swift version `5.6`
 - macOS 12.3 Beta (21E5196i)

**Comment by stephencelis** [comment]
@ferologics How are you depending on TCA? Can you provide the exact git URL and version you're pinning to, etc.?

**Comment by ferologics** [comment]
@stephencelis the url is https://github.com/globekeeper/swift-composable-architecture and we use the [dynamic](https://github.com/globekeeper/swift-composable-architecture/tree/dynamic) branch, which is a fork from version `0.20.0` release with dynamic framework product type (workaround for missing symbols for `OrderedCollections` issue).
