### ISSUE TITLE
Failed to resolve dependencies Dependencies could not be resolved because root depends on 'swift-composable-architecture' 1.2.0. 'swift-composable-architecture' 0.43.0..<1.0.0 is required because 'composable-core-location' 0.3.0 depends on 'swift-composable-architecture' 0.43.0..<1.0.0 and root depends on 'composable-core-location' 0.3.0.

### ISSUE THREAD

**Issue by yosuke1985** [pointfreeco/composable-core-location#39]
**Describe the bug**
Failed to resolve dependencies Dependencies could not be resolved because root depends on 'swift-composable-architecture' 1.2.0.
'swift-composable-architecture' 0.43.0..<1.0.0 is required because 'composable-core-location' 0.3.0 depends on 'swift-composable-architecture' 0.43.0..<1.0.0 and root depends on 'composable-core-location' 0.3.0.

**To Reproduce**
install TCA version 1.2.0 and Composable core location 0.3.0

**Comment by stephencelis** [comment]
@yosuke1985 There's an open PR, https://github.com/pointfreeco/composable-core-location/pull/29, tracking support for TCA 1.x.

**Comment by yosuke1985** [comment]
ok thank you!
